/** Otomatik: tools/build-gloss.mjs */
(function () {
  'use strict';
  window.KDO_GLOSS = {
    th: {
  "hello": "สวัสดี",
  "hello!": "สวัสดี!",
  "goodbye": "ลาก่อน",
  "thanks": "ขอบคุณ",
  "please": "กรุณา",
  "yes": "ใช่",
  "no": "ไม่",
  "good morning": "สวัสดีตอนเช้า",
  "good morning!": "สวัสดีตอนเช้า!",
  "good evening": "สวัสดีตอนเย็น",
  "how are you?": "สบายดีไหม?",
  "I am fine": "สบายดี",
  "I am fine, thanks": "สบายดี ขอบคุณ",
  "what is your name?": "คุณชื่ออะไร?",
  "my name is Ali": "ฉันชื่ออาลี",
  "my name is Anna": "ฉันชื่อแอนนา",
  "nice to meet you": "ยินดีที่ได้รู้จัก",
  "today": "วันนี้",
  "tomorrow": "พรุ่งนี้",
  "yesterday": "เมื่อวาน",
  "friend": "เพื่อน",
  "city": "เมือง",
  "price": "ราคา",
  "room": "ห้อง",
  "house": "บ้าน",
  "hotel": "โรงแรม",
  "hospital": "โรงพยาบาล",
  "doctor": "หมอ",
  "school": "โรงเรียน",
  "university": "มหาวิทยาลัย",
  "student": "นักเรียน",
  "teacher": "ครู",
  "work": "งาน",
  "office": "สำนักงาน",
  "restaurant": "ร้านอาหาร",
  "market": "ตลาด",
  "street": "ถนน",
  "water": "น้ำ",
  "money": "เงิน",
  "menu": "เมนู",
  "train": "รถไฟ",
  "bus": "รถบัส",
  "metro": "รถไฟใต้ดิน",
  "airport": "สนามบิน",
  "country": "ประเทศ",
  "language": "ภาษา",
  "internet": "อินเทอร์เน็ต",
  "email": "อีเมล",
  "message": "ข้อความ",
  "party": "ปาร์ตี้",
  "cinema": "โรงภาพยนตร์",
  "music": "ดนตรี",
  "hobby": "งานอดิเรก",
  "weather": "สภาพอากาศ",
  "rain": "ฝน",
  "happy": "มีความสุข",
  "sad": "เศร้า",
  "tired": "เหนื่อย",
  "beautiful": "สวย",
  "cheap": "ถูก",
  "expensive": "แพง",
  "important": "สำคัญ",
  "color": "สี",
  "card": "บัตร",
  "key": "กุญแจ",
  "table": "โต๊ะ",
  "apartment": "อพาร์ตเมนต์",
  "pharmacy": "ร้านขายยา",
  "travel": "การเดินทาง",
  "education": "การศึกษา",
  "history": "ประวัติศาสตร์",
  "opinion": "ความคิดเห็น",
  "where?": "ที่ไหน?",
  "what time is it?": "กี่โมงแล้ว?",
  "see you": "แล้วเจอกัน",
  "question": "คำถาม",
  "answer": "คำตอบ",
  "to read": "อ่าน",
  "to write": "เขียน",
  "to call": "โทร",
  "to help": "ช่วย",
  "to learn": "เรียน",
  "to buy": "ซื้อ",
  "Doğru kelimeyi seç.": "เลือกคำที่ถูกต้อง",
  "İkinci ifadeyi seç.": "เลือกประโยคที่สอง",
  "Merhaba": "สวัสดี",
  "Merhaba!": "สวัสดี!",
  "Günaydın": "สวัสดีตอนเช้า",
  "Günaydın!": "สวัสดีตอนเช้า!",
  "İyi akşamlar": "สวัสดีตอนเย็น",
  "Hoşça kal": "ลาก่อน",
  "Teşekkürler": "ขอบคุณ",
  "Lütfen": "กรุณา",
  "Evet": "ใช่",
  "Hayır": "ไม่",
  "Nasılsın?": "สบายดีไหม?",
  "İyiyim.": "สบายดี",
  "Benim adım Ali.": "ฉันชื่ออาลี",
  "Tanıştığıma memnun oldum.": "ยินดีที่ได้รู้จัก",
  "Adın ne?": "คุณชื่ออะไร?",
  "Bu ne kadar?": "ราคาเท่าไร?",
  "Hesap, lütfen.": "เก็บเงินด้วย",
  "Türkiye": "ตุรกี",
  "Guten Morgen": "สวัสดีตอนเช้า",
  "Guten Tag": "สวัสดี",
  "Hallo": "สวัสดี",
  "Guten Abend": "สวัสดีตอนเย็น",
  "Auf Wiedersehen": "ลาก่อน",
  "Danke": "ขอบคุณ",
  "Bitte": "กรุณา",
  "Ja": "ใช่",
  "Nein": "ไม่",
  "Entschuldigung": "ขอโทษ",
  "En temel selamlaşma ifadesi.": "สำนวนทักทายพื้นฐานที่สุด",
  "En yaygın selamlama.": "การทักทายที่ใช้บ่อยที่สุด",
  "Sabah selamlaması.": "คำทักทายตอนเช้า",
  "Bonjour": "สวัสดี",
  "Bonsoir": "สวัสดีตอนเย็น",
  "Salut": "สวัสดี",
  "Au revoir": "ลาก่อน",
  "Merhaba / Günaydın": "สวัสดี",
  "Selam": "สวัสดี",
  "Hoşça kalın / Görüşmek üzere": "ลาก่อน",
  "Hoşça kalın": "ลาก่อน",
  "Görüşmek üzere": "แล้วเจอกัน",
  "İyi günler": "สวัสดี",
  "Merci": "ขอบคุณ",
  "S'il vous plaît": "กรุณา",
  "Pardon": "ขอโทษ",
  "Oui": "ใช่",
  "Non": "ไม่",
  "Hoşça kalın / Görüşürüz": "ลาก่อน",
  "Hoşça kal / Güle güle": "ลาก่อน",
  "Lütfen / Rica ederim": "กรุณา",
  "Pardon / Affedersiniz": "ขอโทษ",
  "internet / Wi-Fi": "อินเทอร์เน็ต",
  "İyi günler / İyi ö�xleden sonralar": "สวัสดี",
  "Günaydın / İyi günler!": "สวัสดีตอนเช้า",
  "Bu ne kadar? / Kaça?": "ราคาเท่าไร?",
  "Merhaba / Selam": "สวัสดี",
  "Günaydın / İyi günler": "สวัสดีตอนเช้า",
  "Evet / Hayır": "ใช่",
  "İyiyim, teşekkürler.": "สบายดี ขอบคุณ",
  "Hoşça kal.": "ลาก่อน",
  "First Meeting": "สวัสดี!",
  "Benim adım Anna.": "ฉันชื่อแอนนา",
  "İş": "งาน",
  "Ofis": "สำนักงาน",
  "İnternet": "อินเทอร์เน็ต",
  "E-posta": "อีเมล",
  "Soru": "คำถาม",
  "Cevap": "คำตอบ",
  "Work — Basics": "งาน",
  "Work": "งาน",
  "Doktor": "หมอ",
  "Hastane": "โรงพยาบาล",
  "Eczane": "ร้านขายยา",
  "Yardım etmek": "ช่วย",
  "Bugün": "วันนี้",
  "Health — Basics": "หมอ",
  "Health": "หมอ",
  "Aramak": "โทร",
  "Mesaj": "ข้อความ",
  "Yarın": "พรุ่งนี้",
  "Phone — Basics": "โทร",
  "Phone": "โทร",
  "Arkadaş": "เพื่อน",
  "Parti": "ปาร์ตี้",
  "Sinema": "โรงภาพยนตร์",
  "Müzik": "ดนตรี",
  "Mutlu": "มีความสุข",
  "Görüşürüz.": "แล้วเจอกัน",
  "Social — Basics": "เพื่อน",
  "Social": "เพื่อน",
  "Ev": "บ้าน",
  "Daire": "อพาร์ตเมนต์",
  "Oda": "ห้อง",
  "Masa": "โต๊ะ",
  "Anahtar": "กุญแจ",
  "Fiyat": "ราคา",
  "Home — Basics": "บ้าน",
  "Home": "บ้าน",
  "Eğitim": "การศึกษา",
  "Okul": "โรงเรียน",
  "Üniversite": "มหาวิทยาลัย",
  "Öğrenci": "นักเรียน",
  "Öğretmen": "ครู",
  "Okumak": "อ่าน",
  "Yazmak": "เขียน",
  "Öğrenmek": "เรียน",
  "Dil": "ภาษา",
  "Education — Basics": "การศึกษา",
  "Education": "การศึกษา",
  "Ülke": "ประเทศ",
  "Şehir": "เมือง",
  "Countries — Basics": "ประเทศ",
  "Countries": "ประเทศ",
  "Üzgün": "เศร้า",
  "Yorgun": "เหนื่อย",
  "Görüş": "ความคิดเห็น",
  "Emotions — Basics": "มีความสุข",
  "Emotions": "มีความสุข",
  "Hava": "สภาพอากาศ",
  "Yağmur": "ฝน",
  "Seyahat": "การเดินทาง",
  "Weather — Basics": "สภาพอากาศ",
  "Weather": "สภาพอากาศ",
  "Hobi": "งานอดิเรก",
  "Entertainment — Basics": "งานอดิเรก",
  "Entertainment": "งานอดิเรก",
  "Otel": "โรงแรม",
  "Nerede?": "ที่ไหน?",
  "Daily Conversation — Basics": "สวัสดี",
  "Daily Conversation": "สวัสดี",
  "Satın almak": "ซื้อ",
  "Güzel": "สวย",
  "Önemli": "สำคัญ",
  "Ucuz": "ถูก",
  "Pahalı": "แพง",
  "Cadde": "ถนน",
  "Market": "ตลาด",
  "Restoran": "ร้านอาหาร",
  "Havaalanı": "สนามบิน",
  "Su": "น้ำ",
  "Menü": "เมนู",
  "Para": "เงิน",
  "Renk": "สี",
  "Dün": "เมื่อวาน",
  "Saat kaç?": "กี่โมงแล้ว?",
  "Tren": "รถไฟ",
  "Kart": "บัตร",
  "Otobüs": "รถบัส",
  "Metro": "รถไฟใต้ดิน",
  "Tarih": "ประวัติศาสตร์",
  "Time & Date — Basics": "กี่โมงแล้ว?",
  "Time & Date": "กี่โมงแล้ว?",
  "Restaurant — Basics": "ร้านอาหาร",
  "Restaurant": "ร้านอาหาร",
  "Shopping — Basics": "ตลาด",
  "Shopping": "ตลาด",
  "Directions — Basics": "ที่ไหน?",
  "Directions": "ที่ไหน?",
  "Transport — Basics": "รถไฟ",
  "Transport": "รถไฟ",
  "Hotel — Basics": "โรงแรม",
  "Hotel": "โรงแรม",
  "Hallo!": "สวัสดี!",
  "Guten Morgen!": "สวัสดีตอนเช้า!",
  "Tschüss": "ลาก่อน",
  "Ich heiße Ali.": "ฉันชื่ออาลี",
  "Mir geht es gut, danke.": "สบายดี ขอบคุณ",
  "Greetings by Time of Day": "สวัสดีตอนเช้า!",
  "Formal vs Informal Address": "คุณชื่ออะไร?",
  "Freut mich!": "ยินดีที่ได้รู้จัก",
  "How Are You": "สวัสดีตอนเช้า!",
  "die Türkei": "ตุรกี",
  "Mir geht es gut.": "สบายดี",
  "das Internet": "อินเทอร์เน็ต",
  "Wie viel kostet das?": "ราคาเท่าไร?",
  "Die Rechnung, bitte.": "เก็บเงินด้วย",
  "Money — Euro and Cent": "ราคาเท่าไร?",
  "Wie heißt du?": "คุณชื่ออะไร?",
  "Wie spät ist es?": "กี่โมงแล้ว?",
  "die U-Bahn": "รถไฟใต้ดิน",
  "Hello": "สวัสดี",
  "Hello!": "สวัสดี!",
  "Hi": "สวัสดี",
  "Good morning": "สวัสดีตอนเช้า",
  "Goodbye": "ลาก่อน",
  "Please": "กรุณา",
  "Yes": "ใช่",
  "No": "ไม่",
  "My name is Ali.": "ฉันชื่ออาลี",
  "Nice to meet you.": "ยินดีที่ได้รู้จัก",
  "How are you?": "สบายดีไหม?",
  "What is your name?": "คุณชื่ออะไร?",
  "First Steps — Greetings": "สวัสดี!",
  "Good morning!": "สวัสดีตอนเช้า!",
  "How much is this?": "ราคาเท่าไร?",
  "Where?": "ที่ไหน?",
  "What time is it?": "กี่โมงแล้ว?",
  "underground / subway / tube": "รถไฟใต้ดิน",
  "right next to": "ตลาด",
  "Comment tu t'appelles?": "คุณชื่ออะไร?",
  "Je m'appelle Ali.": "ฉันชื่ออาลี",
  "la Turquie": "ตุรกี",
  "Je vais bien.": "สบายดี",
  "Daily conversation": "สวัสดี!",
  "Combien ça coûte?": "ราคาเท่าไร?",
  "L'addition, s'il vous plaît.": "เก็บเงินด้วย",
  "Quelle heure est-il ?": "กี่โมงแล้ว?",
  "Time and Date": "กี่โมงแล้ว?",
  "La note, s'il vous plaît.": "เก็บเงินด้วย",
  "Combien ça coûte ?": "ราคาเท่าไร?",
  "Shopping phrases": "ราคาเท่าไร?",
  "le métro": "รถไฟใต้ดิน",
  "Hola": "สวัสดี",
  "¡Hola!": "สวัสดี!",
  "Buenos días": "สวัสดีตอนเช้า",
  "¡Buenos días!": "สวัสดีตอนเช้า!",
  "Buenas tardes": "สวัสดี",
  "¿Cómo te llamas?": "คุณชื่ออะไร?",
  "Me llamo Ali.": "ฉันชื่ออาลี",
  "Por favor": "กรุณา",
  "Perdón": "ขอโทษ",
  "Informal vs Formal Address": "คุณชื่ออะไร?",
  "Turquía": "ตุรกี",
  "Estoy bien.": "สบายดี",
  "¿Cuánto cuesta?": "ราคาเท่าไร?",
  "¿Cuánto cuesta esto?": "ราคาเท่าไร?",
  "La cuenta, por favor.": "เก็บเงินด้วย",
  "Money �\u001d Euro and Cent": "ราคาเท่าไร?",
  "¿Qué hora es?": "กี่โมงแล้ว?",
  "el metro": "รถไฟใต้ดิน",
  "Ciao": "สวัสดี",
  "Buongiorno": "สวัสดีตอนเช้า",
  "Buongiorno!": "สวัสดีตอนเช้า!",
  "Buonasera": "สวัสดีตอนเย็น",
  "Arrivederci": "ลาก่อน",
  "Mi chiamo Ali.": "ฉันชื่ออาลี",
  "Per favore": "กรุณา",
  "Sì / No": "ใช่",
  "Informal tu vs Formal Lei": "คุณชื่ออะไร?",
  "Turchia": "ตุรกี",
  "Bene.": "สบายดี",
  "Scusi": "ขอโทษ",
  "Grazie": "ขอบคุณ",
  "Che ore sono?": "กี่โมงแล้ว?",
  "Quanto costa?": "ราคาเท่าไร?",
  "la metropolitana": "รถไฟใต้ดิน",
  "Quanto costa questo?": "ราคาเท่าไร?",
  "Il conto, per favore.": "เก็บเงินด้วย",
  "Money — Euro and Cents": "ราคาเท่าไร?",
  "Telling Time": "กี่โมงแล้ว?",
  "Greeting Patterns": "สวัสดี",
  "Introducing Yourself": "คุณชื่ออะไร?",
  "привет": "สวัสดี",
  "как дела?": "สบายดีไหม?",
  "доброе утро": "สวัสดีตอนเช้า",
  "как тебя зовут?": "คุณชื่ออะไร?",
  "интернет": "อินเทอร์เน็ต",
  "Турция": "ตุรกี",
  "магазин": "ตลาด",
  "цена": "ราคา",
  "дёшево": "ถูก",
  "At Shop": "ราคาเท่าไร?",
  "метро": "รถไฟใต้ดิน",
  "مرحباً": "สวัสดี",
  "كيف حالك؟": "สบายดีไหม?",
  "صباح الخير": "สวัสดีตอนเช้า",
  "ما اسمك؟": "คุณชื่ออะไร?",
  "الإنترنت": "อินเทอร์เน็ต",
  "تركيا": "ตุรกี",
  "المتجر": "ตลาด",
  "السعر": "ราคา",
  "رخيص": "ถูก",
  "المترو": "รถไฟใต้ดิน",
  "你好": "สวัสดี",
  "你好吗？": "สบายดีไหม?",
  "早上好": "สวัสดีตอนเช้า",
  "你叫什么名字？": "คุณชื่ออะไร?",
  "互联网": "อินเทอร์เน็ต",
  "土耳其": "ตุรกี",
  "商店": "ตลาด",
  "价格": "ราคา",
  "便宜": "ถูก",
  "地铁": "รถไฟใต้ดิน",
  "Internet": "อินเทอร์เน็ต"
},
    de: {
  "hello": "hallo",
  "house": "Haus",
  "school": "Schule",
  "office": "Büro",
  "park": "Park",
  "hotel": "Hotel",
  "Merhaba": "Hallo",
  "Merhaba!": "Hallo!",
  "Günaydın": "Guten Morgen",
  "Günaydın!": "Guten Morgen!",
  "İyi akşamlar": "Guten Abend",
  "Hoşça kal": "Auf Wiedersehen",
  "Teşekkürler": "Danke",
  "Lütfen": "Bitte",
  "Evet": "Ja",
  "Hayır": "Nein",
  "Nasılsın?": "Wie geht es dir?",
  "İyiyim.": "Mir geht es gut",
  "Benim adım Ali.": "Ich heiße Ali",
  "Tanıştığıma memnun oldum.": "Freut mich",
  "Adın ne?": "Wie heißt du?",
  "Bu ne kadar?": "Wie viel kostet das?",
  "Hesap, lütfen.": "Die Rechnung, bitte",
  "İyi": "Gut",
  "gün": "Tag",
  "akşam": "Abend",
  "sabah": "Morgen",
  "Bonjour": "Guten Tag",
  "Bonsoir": "Guten Abend",
  "Salut": "Hallo",
  "Au revoir": "Auf Wiedersehen",
  "Merhaba / Günaydın": "Guten Tag",
  "Selam": "Hallo",
  "Hoşça kalın / Görüşmek üzere": "Auf Wiedersehen",
  "Hoşça kal / Güle güle": "Auf Wiedersehen",
  "Lütfen / Rica ederim": "Bitte",
  "Günaydın / İyi günler!": "Guten Morgen",
  "Bu ne kadar? / Kaça?": "Wie viel kostet das?",
  "Merhaba / Selam": "Hallo",
  "Günaydın / İyi günler": "Guten Morgen",
  "Evet / Hayır": "Ja",
  "Ofis": "Büro",
  "Ev": "Haus",
  "Home — Basics": "Haus",
  "Home": "Haus",
  "Okul": "Schule",
  "Park": "Park",
  "Otel": "Hotel",
  "Daily Conversation — Basics": "hallo",
  "Daily Conversation": "hallo",
  "Hotel — Basics": "Hotel",
  "Hotel": "Hotel",
  "Hallo": "Hallo",
  "Hallo!": "Hallo!",
  "Guten Morgen": "Guten Morgen",
  "Guten Morgen!": "Guten Morgen!",
  "Guten Abend": "Guten Abend",
  "Tschüss": "Auf Wiedersehen",
  "Bitte": "Bitte",
  "Ja": "Ja",
  "Nein": "Nein",
  "Ich heiße Ali.": "Ich heiße Ali",
  "Greetings by Time of Day": "Guten Morgen!",
  "Formal vs Informal Address": "Wie heißt du?",
  "Freut mich!": "Freut mich",
  "First Meeting": "Hallo!",
  "How Are You": "Guten Morgen!",
  "Mir geht es gut.": "Mir geht es gut",
  "der Park": "Park",
  "der Tag": "Tag",
  "Wie viel kostet das?": "Wie viel kostet das?",
  "Die Rechnung, bitte.": "Die Rechnung, bitte",
  "Money — Euro and Cent": "Wie viel kostet das?",
  "Wie heißt du?": "Wie heißt du?",
  "der Morgen": "Morgen",
  "der Abend": "Abend",
  "Hello": "Hallo",
  "Hello!": "Hallo!",
  "Hi": "Hallo",
  "Good morning": "Guten Morgen",
  "Goodbye": "Auf Wiedersehen",
  "Please": "Bitte",
  "Yes": "Ja",
  "No": "Nein",
  "My name is Ali.": "Ich heiße Ali",
  "Nice to meet you.": "Freut mich",
  "How are you?": "Wie geht es dir?",
  "What is your name?": "Wie heißt du?",
  "First Steps — Greetings": "Hallo!",
  "Good morning!": "Guten Morgen!",
  "How much is this?": "Wie viel kostet das?",
  "morning": "Morgen",
  "evening": "Abend",
  "day": "Tag",
  "Comment tu t'appelles?": "Wie heißt du?",
  "Je m'appelle Ali.": "Ich heiße Ali",
  "S'il vous plaît": "Bitte",
  "Je vais bien.": "Mir geht es gut",
  "Daily conversation": "Hallo!",
  "le parc": "Park",
  "Combien ça coûte?": "Wie viel kostet das?",
  "L'addition, s'il vous plaît.": "Die Rechnung, bitte",
  "le matin": "Morgen",
  "le soir": "Abend",
  "La note, s'il vous plaît.": "Die Rechnung, bitte",
  "Combien ça coûte ?": "Wie viel kostet das?",
  "Shopping phrases": "Wie viel kostet das?",
  "Hola": "Hallo",
  "¡Hola!": "Hallo!",
  "Buenos días": "Guten Morgen",
  "¡Buenos días!": "Guten Morgen!",
  "¿Cómo te llamas?": "Wie heißt du?",
  "Me llamo Ali.": "Ich heiße Ali",
  "Por favor": "Bitte",
  "Informal vs Formal Address": "Wie heißt du?",
  "Estoy bien.": "Mir geht es gut",
  "el parque": "Park",
  "el día": "Tag",
  "¿Cuánto cuesta?": "Wie viel kostet das?",
  "¿Cuánto cuesta esto?": "Wie viel kostet das?",
  "La cuenta, por favor.": "Die Rechnung, bitte",
  "Money �\u001d Euro and Cent": "Wie viel kostet das?",
  "la mañana": "Morgen",
  "Ciao": "Hallo",
  "Buongiorno": "Guten Morgen",
  "Buongiorno!": "Guten Morgen!",
  "Buonasera": "Guten Abend",
  "Mi chiamo Ali.": "Ich heiße Ali",
  "Per favore": "Bitte",
  "Sì / No": "Ja",
  "Informal tu vs Formal Lei": "Wie heißt du?",
  "Bene.": "Mir geht es gut",
  "Grazie": "Danke",
  "la mattina": "Morgen",
  "la sera": "Abend",
  "Quanto costa?": "Wie viel kostet das?",
  "Quanto costa questo?": "Wie viel kostet das?",
  "Il conto, per favore.": "Die Rechnung, bitte",
  "Money — Euro and Cents": "Wie viel kostet das?",
  "Greeting Patterns": "Hallo",
  "Introducing Yourself": "Wie heißt du?",
  "привет": "Hallo",
  "как дела?": "Wie geht es dir?",
  "доброе утро": "Guten Morgen",
  "как тебя зовут?": "Wie heißt du?",
  "утро": "Morgen",
  "вечер": "Abend",
  "At Shop": "Wie viel kostet das?",
  "مرحباً": "Hallo",
  "كيف حالك؟": "Wie geht es dir?",
  "صباح الخير": "Guten Morgen",
  "ما اسمك؟": "Wie heißt du?",
  "الصباح": "Morgen",
  "المساء": "Abend",
  "你好": "Hallo",
  "你好吗？": "Wie geht es dir?",
  "早上好": "Guten Morgen",
  "你叫什么名字？": "Wie heißt du?",
  "早上": "Morgen",
  "晚上": "Abend",
  "Sabah": "Morgen"
},
    es: {
  "hello": "hola",
  "hello!": "¡hola!",
  "goodbye": "adiós",
  "thanks": "gracias",
  "please": "por favor",
  "yes": "sí",
  "no": "no",
  "good morning": "buenos días",
  "good morning!": "¡buenos días!",
  "good evening": "buenas tardes",
  "how are you?": "¿cómo estás?",
  "I am fine": "estoy bien",
  "I am fine, thanks": "estoy bien, gracias",
  "what is your name?": "¿cómo te llamas?",
  "my name is Ali": "me llamo Ali",
  "my name is Anna": "me llamo Anna",
  "nice to meet you": "encantado de conocerte",
  "today": "hoy",
  "tomorrow": "mañana",
  "yesterday": "ayer",
  "friend": "amigo",
  "city": "ciudad",
  "price": "precio",
  "room": "habitación",
  "house": "casa",
  "hotel": "hotel",
  "hospital": "hospital",
  "doctor": "médico",
  "school": "escuela",
  "university": "universidad",
  "student": "estudiante",
  "teacher": "profesor",
  "work": "trabajo",
  "office": "oficina",
  "restaurant": "restaurante",
  "market": "mercado",
  "street": "calle",
  "water": "agua",
  "money": "dinero",
  "menu": "menú",
  "train": "tren",
  "bus": "autobús",
  "metro": "metro",
  "airport": "aeropuerto",
  "country": "país",
  "language": "idioma",
  "internet": "internet",
  "email": "correo",
  "message": "mensaje",
  "party": "fiesta",
  "cinema": "cine",
  "music": "música",
  "hobby": "afición",
  "weather": "tiempo",
  "rain": "lluvia",
  "happy": "feliz",
  "sad": "triste",
  "tired": "cansado",
  "beautiful": "bonito",
  "cheap": "barato",
  "expensive": "caro",
  "important": "importante",
  "color": "color",
  "card": "tarjeta",
  "key": "llave",
  "table": "mesa",
  "apartment": "apartamento",
  "pharmacy": "farmacia",
  "travel": "viaje",
  "education": "educación",
  "history": "historia",
  "opinion": "opinión",
  "where?": "¿dónde?",
  "what time is it?": "¿qué hora es?",
  "see you": "hasta luego",
  "question": "pregunta",
  "answer": "respuesta",
  "to read": "leer",
  "to write": "escribir",
  "to call": "llamar",
  "to help": "ayudar",
  "to learn": "aprender",
  "to buy": "comprar",
  "park": "parque",
  "bank": "banco",
  "shop": "tienda",
  "store": "tienda",
  "food": "comida",
  "zero": "cero",
  "one": "uno",
  "two": "dos",
  "three": "tres",
  "four": "cuatro",
  "five": "cinco",
  "six": "seis",
  "seven": "siete",
  "eight": "ocho",
  "nine": "nueve",
  "ten": "diez",
  "eleven": "once",
  "twelve": "doce",
  "thirteen": "trece",
  "fourteen": "catorce",
  "fifteen": "quince",
  "sixteen": "dieciséis",
  "seventeen": "diecisiete",
  "eighteen": "dieciocho",
  "nineteen": "diecinueve",
  "twenty": "veinte",
  "thirty": "treinta",
  "forty": "cuarenta",
  "fifty": "cincuenta",
  "sixty": "sesenta",
  "seventy": "setenta",
  "eighty": "ochenta",
  "ninety": "noventa",
  "hundred": "cien",
  "thousand": "mil",
  "twenty-one": "veintiuno",
  "thirty-two": "treinta y dos",
  "one hundred five": "ciento cinco",
  "three hundred fifty": "trescientos cincuenta",
  "ten thousand": "diez mil",
  "drink": "bebida",
  "coffee": "café",
  "tea": "té",
  "bread": "pan",
  "milk": "leche",
  "morning": "mañana",
  "evening": "tarde",
  "night": "noche",
  "week": "semana",
  "month": "mes",
  "year": "año",
  "time": "hora",
  "name": "nombre",
  "age": "edad",
  "phone": "teléfono",
  "address": "dirección",
  "door": "puerta",
  "window": "ventana",
  "car": "coche",
  "taxi": "taxi",
  "ticket": "billete",
  "passport": "pasaporte",
  "map": "mapa",
  "help": "ayuda",
  "problem": "problema",
  "open": "abierto",
  "closed": "cerrado",
  "big": "grande",
  "small": "pequeño",
  "new": "nuevo",
  "old": "viejo",
  "good": "bueno",
  "bad": "malo",
  "hot": "caliente",
  "cold": "frío",
  "fast": "rápido",
  "slow": "lento",
  "near": "cerca",
  "far": "lejos",
  "left": "izquierda",
  "right": "derecha",
  "straight": "recto",
  "here": "aquí",
  "there": "allí",
  "now": "ahora",
  "later": "después",
  "always": "siempre",
  "never": "nunca",
  "good afternoon": "buenas tardes",
  "good night": "buenas noches",
  "sorry": "lo siento",
  "excuse me": "disculpe",
  "welcome": "bienvenido",
  "bathroom": "baño",
  "kitchen": "cocina",
  "garden": "jardín",
  "sea": "mar",
  "beach": "playa",
  "mountain": "montaña",
  "island": "isla",
  "north": "norte",
  "south": "sur",
  "east": "este",
  "west": "oeste",
  "station": "estación",
  "bridge": "puente",
  "church": "iglesia",
  "museum": "museo",
  "library": "biblioteca",
  "police": "policía",
  "fire": "fuego",
  "ambulance": "ambulancia",
  "medicine": "medicina",
  "pain": "dolor",
  "sick": "enfermo",
  "healthy": "sano",
  "family": "familia",
  "mother": "madre",
  "father": "padre",
  "brother": "hermano",
  "sister": "hermana",
  "child": "niño",
  "man": "hombre",
  "woman": "mujer",
  "boy": "niño",
  "girl": "niña",
  "husband": "esposo",
  "wife": "esposa",
  "neighbour": "vecino",
  "suffix": "sufijo",
  "vowel": "vocal",
  "harmony": "armonía",
  "location": "ubicación",
  "plural": "plural",
  "at home": "en casa",
  "at school": "en la escuela",
  "at work": "en el trabajo",
  "in the park": "en el parque",
  "in the hotel": "en el hotel",
  "in the office": "en la oficina",
  "internet / Wi-Fi": "internet",
  "Merhaba": "hola",
  "Günaydın": "buenos días",
  "İyi akşamlar": "buenas tardes",
  "Hoşça kal": "adiós",
  "Teşekkürler": "gracias",
  "Lütfen": "por favor",
  "Evet": "sí",
  "Hayır": "no",
  "Adın ne?": "¿cómo te llamas?",
  "Benim adım Ali.": "me llamo Ali",
  "Tanıştığıma memnun oldum.": "encantado de conocerte",
  "Nasılsın?": "¿cómo estás?",
  "İyiyim.": "estoy bien",
  "Merhaba!": "hola",
  "İyiyim, teşekkürler.": "estoy bien, gracias",
  "Hoşça kal.": "adiós",
  "First Meeting": "¡hola!",
  "Günaydın!": "¡buenos días!",
  "Benim adım Anna.": "me llamo Anna",
  "İş": "trabajo",
  "Ofis": "oficina",
  "İnternet": "internet",
  "E-posta": "correo",
  "Soru": "pregunta",
  "Cevap": "respuesta",
  "Work — Basics": "trabajo",
  "Work": "trabajo",
  "Doktor": "médico",
  "Hastane": "hospital",
  "Eczane": "farmacia",
  "Ağrı": "dolor",
  "İlaç": "medicina",
  "Yardım etmek": "ayudar",
  "Bugün": "hoy",
  "Health — Basics": "médico",
  "Health": "médico",
  "Aramak": "llamar",
  "Mesaj": "mensaje",
  "Yarın": "mañana",
  "Phone — Basics": "llamar",
  "Phone": "llamar",
  "Arkadaş": "amigo",
  "Parti": "fiesta",
  "Sinema": "cine",
  "Müzik": "música",
  "Mutlu": "feliz",
  "Görüşürüz.": "hasta luego",
  "Aile": "familia",
  "Social — Basics": "amigo",
  "Social": "amigo",
  "Ev": "casa",
  "Daire": "apartamento",
  "Oda": "habitación",
  "Mutfak": "cocina",
  "Banyo": "baño",
  "Masa": "mesa",
  "Pencere": "ventana",
  "Kapı": "puerta",
  "Anahtar": "llave",
  "Fiyat": "precio",
  "Home — Basics": "casa",
  "Home": "casa",
  "Eğitim": "educación",
  "Okul": "escuela",
  "Üniversite": "universidad",
  "Öğrenci": "estudiante",
  "Öğretmen": "profesor",
  "Okumak": "leer",
  "Yazmak": "escribir",
  "Öğrenmek": "aprender",
  "Dil": "idioma",
  "Education — Basics": "educación",
  "Education": "educación",
  "Ülke": "país",
  "Şehir": "ciudad",
  "Kuzey": "norte",
  "Güney": "sur",
  "Doğu": "este",
  "Batı": "oeste",
  "Countries — Basics": "país",
  "Countries": "país",
  "Üzgün": "triste",
  "Yorgun": "cansado",
  "Görüş": "opinión",
  "Emotions — Basics": "feliz",
  "Emotions": "feliz",
  "Hava": "tiempo",
  "Yağmur": "lluvia",
  "Sıcak": "caliente",
  "Soğuk": "frío",
  "Sabah": "mañana",
  "Akşam": "tarde",
  "Seyahat": "viaje",
  "Weather — Basics": "tiempo",
  "Weather": "tiempo",
  "Hobi": "afición",
  "Müze": "museo",
  "Entertainment — Basics": "afición",
  "Entertainment": "afición",
  "Park": "parque",
  "Otel": "hotel",
  "Evde": "en casa",
  "Okulda": "en la escuela",
  "Parkta": "en el parque",
  "Locative Suffix": "en casa",
  "Nerede?": "¿dónde?",
  "Daily Conversation — Basics": "hola",
  "Daily Conversation": "hola",
  "Satın almak": "comprar",
  "Yeni": "nuevo",
  "Eski": "viejo",
  "Büyük": "grande",
  "Küçük": "pequeño",
  "Güzel": "bonito",
  "Hızlı": "rápido",
  "Yavaş": "lento",
  "Önemli": "importante",
  "Ucuz": "barato",
  "Pahalı": "caro",
  "Yakın": "cerca",
  "Cadde": "calle",
  "İstasyon": "estación",
  "Market": "mercado",
  "Restoran": "restaurante",
  "Havaalanı": "aeropuerto",
  "Su": "agua",
  "Çay": "té",
  "Kahve": "café",
  "Ekmek": "pan",
  "Menü": "menú",
  "Para": "dinero",
  "Renk": "color",
  "Dün": "ayer",
  "Gece": "noche",
  "Saat kaç?": "¿qué hora es?",
  "Sağlıklı": "sano",
  "Tren": "tren",
  "Bir": "uno",
  "İki": "dos",
  "Üç": "tres",
  "Dört": "cuatro",
  "Beş": "cinco",
  "On": "diez",
  "Yirmi": "veinte",
  "Elli": "cincuenta",
  "Yüz": "cien",
  "Bin": "mil",
  "Kart": "tarjeta",
  "Otobüs": "autobús",
  "Metro": "metro",
  "Bilet": "billete",
  "Pasaport": "pasaporte",
  "Harita": "mapa",
  "Dağ": "montaña",
  "Deniz": "mar",
  "Ada": "isla",
  "Banka": "banco",
  "Tarih": "historia",
  "İyi": "bueno",
  "Kötü": "malo",
  "Time & Date — Basics": "¿qué hora es?",
  "Time & Date": "¿qué hora es?",
  "Yemek": "comida",
  "Affedersiniz.": "disculpe",
  "Sonra": "después",
  "Restaurant — Basics": "restaurante",
  "Restaurant": "restaurante",
  "Shopping — Basics": "mercado",
  "Shopping": "mercado",
  "Sol": "izquierda",
  "Sağ": "derecha",
  "Dümdüz": "recto",
  "Uzak": "lejos",
  "Taksi": "taxi",
  "Directions — Basics": "¿dónde?",
  "Directions": "¿dónde?",
  "Transport — Basics": "tren",
  "Transport": "tren",
  "Hotel — Basics": "hotel",
  "Hotel": "hotel",
  "Hallo": "hola",
  "Hallo!": "hola",
  "Guten Morgen": "buenos días",
  "Guten Morgen!": "¡buenos días!",
  "Guten Abend": "buenas tardes",
  "Tschüss": "adiós",
  "Bitte": "por favor",
  "Ja": "sí",
  "Nein": "no",
  "Ich heiße Ali.": "me llamo Ali",
  "Mir geht es gut, danke.": "estoy bien, gracias",
  "Greetings by Time of Day": "¡buenos días!",
  "Formal vs Informal Address": "¿cómo te llamas?",
  "Freut mich!": "encantado de conocerte",
  "How Are You": "¡buenos días!",
  "Mir geht es gut.": "estoy bien",
  "der Park": "parque",
  "das Internet": "internet",
  "Wie heißt du?": "¿cómo te llamas?",
  "Wie spät ist es?": "¿qué hora es?",
  "die U-Bahn": "metro",
  "Hello": "hola",
  "Hello!": "hola",
  "Good morning": "buenos días",
  "Goodbye": "adiós",
  "Please": "por favor",
  "Yes": "sí",
  "No": "no",
  "My name is Ali.": "me llamo Ali",
  "Nice to meet you.": "encantado de conocerte",
  "How are you?": "¿cómo estás?",
  "What is your name?": "¿cómo te llamas?",
  "First Steps — Greetings": "hola",
  "Good morning!": "¡buenos días!",
  "Where?": "¿dónde?",
  "What time is it?": "¿qué hora es?",
  "underground / subway / tube": "metro",
  "polite particle": "cerca",
  "right next to": "mercado",
  "Bonjour": "hola",
  "Bonsoir": "buenas tardes",
  "Comment tu t'appelles?": "¿cómo te llamas?",
  "Je m'appelle Ali.": "me llamo Ali",
  "S'il vous plaît": "por favor",
  "Je vais bien.": "estoy bien",
  "Daily conversation": "hola",
  "le parc": "parque",
  "Quelle heure est-il ?": "¿qué hora es?",
  "Time and Date": "¿qué hora es?",
  "le métro": "metro",
  "Hola": "hola",
  "¡Hola!": "hola",
  "Buenos días": "buenos días",
  "¡Buenos días!": "¡buenos días!",
  "¿Cómo te llamas?": "¿cómo te llamas?",
  "Me llamo Ali.": "me llamo Ali",
  "Por favor": "por favor",
  "Informal vs Formal Address": "¿cómo te llamas?",
  "Estoy bien.": "estoy bien",
  "el parque": "parque",
  "¿Qué hora es?": "¿qué hora es?",
  "el metro": "metro",
  "Ciao": "hola",
  "Buongiorno": "buenos días",
  "Buongiorno!": "¡buenos días!",
  "Buonasera": "buenas tardes",
  "Mi chiamo Ali.": "me llamo Ali",
  "Per favore": "por favor",
  "Sì / No": "sí",
  "Informal tu vs Formal Lei": "¿cómo te llamas?",
  "Bene.": "estoy bien",
  "Grazie": "gracias",
  "Che ore sono?": "¿qué hora es?",
  "la metropolitana": "metro",
  "Telling Time": "¿qué hora es?",
  "Greeting Patterns": "hola",
  "Introducing Yourself": "¿cómo te llamas?",
  "привет": "hola",
  "как дела?": "¿cómo estás?",
  "доброе утро": "buenos días",
  "как тебя зовут?": "¿cómo te llamas?",
  "интернет": "internet",
  "магазин": "mercado",
  "цена": "precio",
  "дёшево": "barato",
  "метро": "metro",
  "مرحباً": "hola",
  "كيف حالك؟": "¿cómo estás?",
  "صباح الخير": "buenos días",
  "ما اسمك؟": "¿cómo te llamas?",
  "الإنترنت": "internet",
  "المتجر": "mercado",
  "السعر": "precio",
  "رخيص": "barato",
  "المترو": "metro",
  "你好": "hola",
  "你好吗？": "¿cómo estás?",
  "早上好": "buenos días",
  "你叫什么名字？": "¿cómo te llamas?",
  "互联网": "internet",
  "商店": "mercado",
  "价格": "precio",
  "便宜": "barato",
  "地铁": "metro",
  "Internet": "internet"
},
    fr: {
  "house": "maison",
  "school": "école",
  "office": "bureau",
  "park": "parc",
  "hotel": "hôtel",
  "hello": "bonjour",
  "thanks": "merci",
  "please": "s'il vous plaît",
  "yes": "oui",
  "no": "non",
  "restaurant": "restaurant",
  "street": "rue",
  "water": "eau",
  "money": "argent",
  "friend": "ami",
  "city": "ville",
  "price": "prix",
  "room": "chambre",
  "work": "travail",
  "doctor": "médecin",
  "Merhaba": "bonjour",
  "Teşekkürler": "merci",
  "Lütfen": "s'il vous plaît",
  "Evet": "oui",
  "Hayır": "non",
  "Merhaba!": "bonjour",
  "İş": "travail",
  "Ofis": "bureau",
  "Work — Basics": "travail",
  "Work": "travail",
  "Doktor": "médecin",
  "Health — Basics": "médecin",
  "Health": "médecin",
  "Arkadaş": "ami",
  "Social — Basics": "ami",
  "Social": "ami",
  "Ev": "maison",
  "Oda": "chambre",
  "Fiyat": "prix",
  "Home — Basics": "maison",
  "Home": "maison",
  "Okul": "école",
  "Şehir": "ville",
  "Park": "parc",
  "Otel": "hôtel",
  "Daily Conversation — Basics": "bonjour",
  "Daily Conversation": "bonjour",
  "Cadde": "rue",
  "Restoran": "restaurant",
  "Su": "eau",
  "Para": "argent",
  "Restaurant — Basics": "restaurant",
  "Restaurant": "restaurant",
  "Hotel — Basics": "hôtel",
  "Hotel": "hôtel",
  "Hallo": "bonjour",
  "Hallo!": "bonjour",
  "Bitte": "s'il vous plaît",
  "Ja": "oui",
  "Nein": "non",
  "First Meeting": "bonjour",
  "der Park": "parc",
  "Hello": "bonjour",
  "Hello!": "bonjour",
  "Please": "s'il vous plaît",
  "Yes": "oui",
  "No": "non",
  "First Steps — Greetings": "bonjour",
  "Bonjour": "bonjour",
  "S'il vous plaît": "s'il vous plaît",
  "Daily conversation": "bonjour",
  "le parc": "parc",
  "Hola": "bonjour",
  "¡Hola!": "bonjour",
  "Por favor": "s'il vous plaît",
  "el parque": "parc",
  "Ciao": "bonjour",
  "Per favore": "s'il vous plaît",
  "Sì / No": "oui",
  "Grazie": "merci",
  "Greeting Patterns": "bonjour",
  "привет": "bonjour",
  "цена": "prix",
  "مرحباً": "bonjour",
  "السعر": "prix",
  "你好": "bonjour",
  "价格": "prix"
},
    it: {
  "house": "casa",
  "school": "scuola",
  "office": "ufficio",
  "park": "parco",
  "hotel": "hotel",
  "hello": "ciao",
  "thanks": "grazie",
  "please": "per favore",
  "yes": "sì",
  "no": "no",
  "Merhaba": "ciao",
  "Teşekkürler": "grazie",
  "Lütfen": "per favore",
  "Evet": "sì",
  "Hayır": "no",
  "Merhaba!": "ciao",
  "Ofis": "ufficio",
  "Ev": "casa",
  "Home — Basics": "casa",
  "Home": "casa",
  "Okul": "scuola",
  "Park": "parco",
  "Otel": "hotel",
  "Daily Conversation — Basics": "ciao",
  "Daily Conversation": "ciao",
  "Hotel — Basics": "hotel",
  "Hotel": "hotel",
  "Hallo": "ciao",
  "Hallo!": "ciao",
  "Bitte": "per favore",
  "Ja": "sì",
  "Nein": "no",
  "First Meeting": "ciao",
  "der Park": "parco",
  "Hello": "ciao",
  "Hello!": "ciao",
  "Please": "per favore",
  "Yes": "sì",
  "No": "no",
  "First Steps — Greetings": "ciao",
  "Bonjour": "ciao",
  "S'il vous plaît": "per favore",
  "Daily conversation": "ciao",
  "le parc": "parco",
  "Hola": "ciao",
  "¡Hola!": "ciao",
  "Por favor": "per favore",
  "el parque": "parco",
  "Ciao": "ciao",
  "Per favore": "per favore",
  "Sì / No": "sì",
  "Grazie": "grazie",
  "Greeting Patterns": "ciao",
  "привет": "ciao",
  "مرحباً": "ciao",
  "你好": "ciao"
},
    ru: {
  "house": "дом",
  "school": "школа",
  "office": "офис",
  "park": "парк",
  "hotel": "отель",
  "hello": "привет",
  "thanks": "спасибо",
  "please": "пожалуйста",
  "yes": "да",
  "no": "нет",
  "Merhaba": "привет",
  "Teşekkürler": "спасибо",
  "Lütfen": "пожалуйста",
  "Evet": "да",
  "Hayır": "нет",
  "Merhaba!": "привет",
  "Ofis": "офис",
  "Ev": "дом",
  "Home — Basics": "дом",
  "Home": "дом",
  "Okul": "школа",
  "Park": "парк",
  "Otel": "отель",
  "Daily Conversation — Basics": "привет",
  "Daily Conversation": "привет",
  "Hotel — Basics": "отель",
  "Hotel": "отель",
  "Hallo": "привет",
  "Hallo!": "привет",
  "Bitte": "пожалуйста",
  "Ja": "да",
  "Nein": "нет",
  "First Meeting": "привет",
  "der Park": "парк",
  "Hello": "привет",
  "Hello!": "привет",
  "Please": "пожалуйста",
  "Yes": "да",
  "No": "нет",
  "First Steps — Greetings": "привет",
  "Bonjour": "привет",
  "S'il vous plaît": "пожалуйста",
  "Daily conversation": "привет",
  "le parc": "парк",
  "Hola": "привет",
  "¡Hola!": "привет",
  "Por favor": "пожалуйста",
  "el parque": "парк",
  "Ciao": "привет",
  "Per favore": "пожалуйста",
  "Sì / No": "да",
  "Grazie": "спасибо",
  "Greeting Patterns": "привет",
  "привет": "привет",
  "مرحباً": "привет",
  "你好": "привет"
},
    ar: {
  "house": "منزل",
  "school": "مدرسة",
  "office": "مكتب",
  "park": "حديقة",
  "hotel": "فندق",
  "hello": "مرحبا",
  "thanks": "شكرا",
  "please": "من فضلك",
  "yes": "نعم",
  "no": "لا",
  "Merhaba": "مرحبا",
  "Teşekkürler": "شكرا",
  "Lütfen": "من فضلك",
  "Evet": "نعم",
  "Hayır": "لا",
  "Merhaba!": "مرحبا",
  "Ofis": "مكتب",
  "Ev": "منزل",
  "Home — Basics": "منزل",
  "Home": "منزل",
  "Okul": "مدرسة",
  "Park": "حديقة",
  "Otel": "فندق",
  "Daily Conversation — Basics": "مرحبا",
  "Daily Conversation": "مرحبا",
  "Hotel — Basics": "فندق",
  "Hotel": "فندق",
  "Hallo": "مرحبا",
  "Hallo!": "مرحبا",
  "Bitte": "من فضلك",
  "Ja": "نعم",
  "Nein": "لا",
  "First Meeting": "مرحبا",
  "der Park": "حديقة",
  "Hello": "مرحبا",
  "Hello!": "مرحبا",
  "Please": "من فضلك",
  "Yes": "نعم",
  "No": "لا",
  "First Steps — Greetings": "مرحبا",
  "Bonjour": "مرحبا",
  "S'il vous plaît": "من فضلك",
  "Daily conversation": "مرحبا",
  "le parc": "حديقة",
  "Hola": "مرحبا",
  "¡Hola!": "مرحبا",
  "Por favor": "من فضلك",
  "el parque": "حديقة",
  "Ciao": "مرحبا",
  "Per favore": "من فضلك",
  "Sì / No": "نعم",
  "Grazie": "شكرا",
  "Greeting Patterns": "مرحبا",
  "привет": "مرحبا",
  "مرحباً": "مرحبا",
  "你好": "مرحبا"
},
    zh: {
  "house": "房子",
  "school": "学校",
  "office": "办公室",
  "park": "公园",
  "hotel": "酒店",
  "hello": "你好",
  "thanks": "谢谢",
  "please": "请",
  "yes": "是",
  "no": "不",
  "Merhaba": "你好",
  "Teşekkürler": "谢谢",
  "Lütfen": "请",
  "Evet": "是",
  "Hayır": "不",
  "Merhaba!": "你好",
  "Ofis": "办公室",
  "Ev": "房子",
  "Home — Basics": "房子",
  "Home": "房子",
  "Okul": "学校",
  "Park": "公园",
  "Otel": "酒店",
  "Daily Conversation — Basics": "你好",
  "Daily Conversation": "你好",
  "Hotel — Basics": "酒店",
  "Hotel": "酒店",
  "Hallo": "你好",
  "Hallo!": "你好",
  "Bitte": "请",
  "Ja": "是",
  "Nein": "不",
  "First Meeting": "你好",
  "der Park": "公园",
  "Hello": "你好",
  "Hello!": "你好",
  "Please": "请",
  "Yes": "是",
  "No": "不",
  "First Steps — Greetings": "你好",
  "Bonjour": "你好",
  "S'il vous plaît": "请",
  "Daily conversation": "你好",
  "le parc": "公园",
  "Hola": "你好",
  "¡Hola!": "你好",
  "Por favor": "请",
  "el parque": "公园",
  "Ciao": "你好",
  "Per favore": "请",
  "Sì / No": "是",
  "Grazie": "谢谢",
  "Greeting Patterns": "你好",
  "привет": "你好",
  "مرحباً": "你好",
  "你好": "你好"
}
  };
})();
