#!/usr/bin/env node
/** Assembles clean gen-italian-lessons.mjs from German template + Italian L1-L3 */
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const german = readFileSync(join(__dirname, 'gen-german-lessons.mjs'), 'utf8');
const partial = readFileSync(join(__dirname, 'gen-italian-lessons.mjs'), 'utf8');

const header = partial.slice(0, partial.indexOf('// ─── Lesson 1:'));
let l1l3 = partial.slice(
  partial.indexOf('// ─── Lesson 1:'),
  partial.indexOf('// ─── Lessons 4–20:')
);
l1l3 = l1l3.replace(
  /const L3 = \{\s*\.\.\.scenario\('Numbers & Money',([\s\S]*?)\),\s*numbers: IT_NUMBERS,\s*compounds: IT_COMPOUNDS\s*\};/,
  "const L3 = scenario('Numbers & Money',$1);"
);

let tail = german.slice(german.indexOf('// ─── Lessons 4–20:'));

// Metadata
tail = tail
  .replace(/German Lesson/g, 'Italian Lesson')
  .replace(/Almanca/g, 'İtalyanca')
  .replace(/Almanya/g, 'İtalya')
  .replace(/Almancanın/g, 'İtalyancanın')
  .replace(/Almancada/g, 'İtalyancada')
  .replace(/Deutsch lernen/g, 'italiano imparare')
  .replace(/Deutsch\./g, 'italiano.')
  .replace(/Deutsch /g, 'italiano ')
  .replace(/Artikel & sein/g, 'Articoli & essere')
  .replace(/Grundverben/g, 'Verbi fondamentali')
  .replace(/German lesson/g, 'Italian lesson')
  .replace(/Generated \$\{created\}\/49 German/g, 'Generated ${created}/49 Italian')
  .replace(/2: \['Artikel & sein', L2\]/, "2: ['Articoli & essere', L2]");

// Safe phrase replacements (length >= 5, sorted longest first)
const PHRASES = [
  ['Wie spät ist es?', 'Che ore sono?'],
  ['Es ist drei Uhr', 'Sono le tre'],
  ['Es ist zehn Uhr', 'Sono le dieci'],
  ['Heute ist Montag', 'Oggi è lunedì'],
  ['Heute ist Mittwoch', 'Oggi è mercoledì'],
  ['Wann haben Sie Zeit?', 'Quando ha tempo?'],
  ['Am Dienstag um zehn Uhr?', 'Martedì alle dieci?'],
  ['Ja, das passt. Bis Dienstag!', 'Sì, va bene. A martedì!'],
  ['Bis Dienstag. Auf Wiedersehen!', 'A martedì. Arrivederci!'],
  ['Entschuldigung, wie spät ist es?', 'Scusi, che ore sono?'],
  ['Morgen habe ich Zeit.', 'Domani ho tempo.'],
  ['Um neun Uhr, bitte.', 'Alle nove, per favore.'],
  ['Einen Tisch für zwei, bitte.', 'Un tavolo per due, per favore.'],
  ['Einen Tisch für drei, bitte.', 'Un tavolo per tre, per favore.'],
  ['Ich hätte gern...', 'Vorrei...'],
  ['Ich hätte gern einen Kaffee.', 'Vorrei un caffè.'],
  ['Ich hätte gern die Suppe, bitte.', 'Vorrei la zuppa, per favore.'],
  ['Die Rechnung, bitte.', 'Il conto, per favore.'],
  ['Was empfehlen Sie?', 'Cosa consiglia?'],
  ['Ohne Zwiebeln, bitte.', 'Senza cipolle, per favore.'],
  ['Das schmeckt sehr gut!', 'È buonissimo!'],
  ['Ich bin allergisch gegen Nüsse.', 'Sono allergico alle noci.'],
  ['Guten Abend! Haben Sie reserviert?', 'Buonasera! Ha prenotato?'],
  ['Wo finde ich...?', 'Dove trovo...?'],
  ['Wie viel kostet das?', 'Quanto costa?'],
  ['Das ist zu teuer.', 'È troppo caro.'],
  ['Kann ich das anprobieren?', 'Posso provarlo?'],
  ['Das passt mir.', 'Mi sta bene.'],
  ['Ich nehme das.', 'Lo prendo.'],
  ['Wo ist der Bahnhof?', 'Dov\\\'è la stazione?'],
  ['Gehen Sie geradeaus.', 'Vada dritto.'],
  ['Dann links.', 'Poi a sinistra.'],
  ['Es ist in der Nähe.', 'È vicino.'],
  ['Entschuldigung, wo ist der Bahnhof?', 'Scusi, dov\\\'è la stazione?'],
  ['Gehen Sie geradeaus, dann links.', 'Vada dritto, poi a sinistra.'],
  ['Eine Fahrkarte nach Berlin, bitte.', 'Un biglietto per Roma, per favore.'],
  ['Eine Fahrkarte nach München, bitte.', 'Un biglietto per Milano, per favore.'],
  ['Ich habe eine Buchung.', 'Ho una prenotazione.'],
  ['Guten Abend! Willkommen im Hotel.', 'Buonasera! Benvenuto in hotel.'],
  ['Was sind Sie von Beruf?', 'Qual è la sua professione?'],
  ['Schönen Feierabend!', 'Buona serata!'],
  ['Ich bin krank.', 'Sono malato.'],
  ['Ich habe Fieber.', 'Ho la febbre.'],
  ['Gute Besserung!', 'Guarisci presto!'],
  ['Entschuldigung', 'Scusi'],
  ['Kein Problem', 'Nessun problema'],
  ['Natürlich', 'Certo'],
  ['Verstehen Sie?', 'Capisce?'],
  ['Ich verstehe nicht.', 'Non capisco.'],
  ['Langsam, bitte.', 'Piano, per favore.'],
  ['Alles klar!', 'Tutto chiaro!'],
  ['Auf Wiedersehen', 'Arrivederci'],
  ['Guten Tag!', 'Buongiorno!'],
  ['Guten Morgen!', 'Buongiorno!'],
  ['Guten Abend!', 'Buonasera!'],
  ['Herzlichen Glückwunsch!', 'Congratulazioni!'],
  ['Prost!', 'Cin cin!'],
  ['Willkommen!', 'Benvenuto!'],
  ['Schönes Wochenende!', 'Buon fine settimana!'],
  ['Es tut mir leid.', 'Mi dispiace.'],
  ['Ich lerne Deutsch.', 'Imparo l\\\'italiano.'],
  ['Ich lerne Italiano.', 'Imparo l\\\'italiano.'],
  ['Warum lernst du Deutsch?', 'Perché impari l\\\'italiano?'],
  ['der Morgen', 'la mattina'],
  ['der Nachmittag', 'il pomeriggio'],
  ['der Abend', 'la sera'],
  ['die Nacht', 'la notte'],
  ['heute', 'oggi'],
  ['morgen', 'domani'],
  ['gestern', 'ieri'],
  ['Montag', 'lunedì'],
  ['Dienstag', 'martedì'],
  ['Mittwoch', 'mercoledì'],
  ['Donnerstag', 'giovedì'],
  ['Freitag', 'venerdì'],
  ['Samstag', 'sabato'],
  ['Sonntag', 'domenica'],
  ['der Januar', 'gennaio'],
  ['der Juli', 'luglio'],
  ['Wann?', 'Quando?'],
  ['die Speisekarte', 'il menu'],
  ['bestellen', 'ordinare'],
  ['die Vorspeise', 'l\\\'antipasto'],
  ['das Hauptgericht', 'il piatto principale'],
  ['der Nachtisch', 'il dolce'],
  ['das Getränk', 'la bevanda'],
  ['das Wasser', 'l\\\'acqua'],
  ['der Kaffee', 'il caffè'],
  ['der Tee', 'il tè'],
  ['der Saft', 'il succo'],
  ['das Brot', 'il pane'],
  ['die Suppe', 'la zuppa'],
  ['der Salat', 'l\\\'insalata'],
  ['vegetarisch', 'vegetariano'],
  ['lecker', 'delizioso'],
  ['die Rechnung', 'il conto'],
  ['die Reservierung', 'la prenotazione'],
  ['Guten Appetit!', 'Buon appetito!'],
  ['zu teuer', 'troppo caro'],
  ['billig', 'economico'],
  ['der Rabatt', 'lo sconto'],
  ['die Größe', 'la taglia'],
  ['die Farbe', 'il colore'],
  ['anprobieren', 'provare'],
  ['passen', 'andare bene'],
  ['kaufen', 'comprare'],
  ['bezahlen', 'pagare'],
  ['Wo ist...?', 'Dov\\\'è...?'],
  ['links', 'a sinistra'],
  ['rechts', 'a destra'],
  ['geradeaus', 'dritto'],
  ['die Straße', 'la strada'],
  ['der Bahnhof', 'la stazione'],
  ['der Zug', 'il treno'],
  ['der Bus', 'l\\\'autobus'],
  ['die U-Bahn', 'la metropolitana'],
  ['das Flugzeug', 'l\\\'aereo'],
  ['der Flughafen', 'l\\\'aeroporto'],
  ['die Fahrkarte', 'il biglietto'],
  ['das Hotel', 'l\\\'hotel'],
  ['das Zimmer', 'la camera'],
  ['Frühstück', 'la colazione'],
  ['die Arbeit', 'il lavoro'],
  ['der Beruf', 'la professione'],
  ['das Büro', 'l\\\'ufficio'],
  ['der Arzt / die Ärztin', 'il medico / la medica'],
  ['das Krankenhaus', 'l\\\'ospedale'],
  ['die Apotheke', 'la farmacia'],
  ['krank', 'malato'],
  ['die Schule', 'la scuola'],
  ['die Universität', 'l\\\'università'],
  ['der Student / die Studentin', 'lo studente / la studentessa'],
  ['der Lehrer / die Lehrerin', 'l\'insegnante'],
  ['lernen', 'imparare'],
  ['Deutschland', 'Italia'],
  ['die Türkei', 'la Turchia'],
  ['Frankreich', 'Francia'],
  ['Italien', 'Italia'],
  ['Spanien', 'Spagna'],
  ['das Wetter', 'il tempo'],
  ['die Sonne', 'il sole'],
  ['der Regen', 'la pioggia'],
  ['der Schnee', 'la neve'],
  ['warm', 'caldo'],
  ['kalt', 'freddo'],
  ['das Kino', 'il cinema'],
  ['das Buch', 'il libro'],
  ['lesen', 'leggere'],
  ['Musik', 'musica'],
  ['Sport', 'sport'],
  ['sein', 'essere'],
  ['haben', 'avere'],
  ['werden', 'diventare'],
  ['machen', 'fare'],
  ['gehen', 'andare'],
  ['kommen', 'venire'],
  ['sehen', 'vedere'],
  ['wissen', 'sapere'],
  ['denken', 'pensare'],
  ['wollen', 'volere'],
  ['müssen', 'dovere'],
  ['können', 'potere'],
  ['mögen', 'amare'],
  ['sagen', 'dire'],
  ['fragen', 'chiedere'],
  ['geben', 'dare'],
  ['nehmen', 'prendere'],
  ['finden', 'trovare'],
  ['bleiben', 'restare'],
  ['helfen', 'aiutare'],
  ['arbeiten', 'lavorare'],
  ['groß', 'grande'],
  ['klein', 'piccolo'],
  ['gut', 'buono'],
  ['schlecht', 'cattivo'],
  ['neu', 'nuovo'],
  ['schnell', 'veloce'],
  ['langsam', 'lento'],
  ['einfach', 'facile'],
  ['schwer', 'difficile'],
  ['schön', 'bello'],
  ['interessant', 'interessante'],
  ['langweilig', 'noioso'],
  ['teuer', 'caro'],
  ['wichtig', 'importante'],
  ['richtig', 'giusto'],
  ['falsch', 'sbagliato'],
  ['der Mann', 'l\'uomo'],
  ['die Frau', 'la donna'],
  ['das Kind', 'il bambino'],
  ['der Vater', 'il padre'],
  ['die Mutter', 'la madre'],
  ['der Bruder', 'il fratello'],
  ['die Schwester', 'la sorella'],
  ['die Familie', 'la famiglia'],
  ['die Stadt', 'la città'],
  ['der Park', 'il parco'],
  ['das Restaurant', 'il ristorante'],
  ['der Apfel', 'la mela'],
  ['die Banane', 'la banana'],
  ['der Käse', 'il formaggio'],
  ['der Fisch', 'il pesce'],
  ['rot', 'rosso'],
  ['blau', 'blu'],
  ['grün', 'verde'],
  ['gelb', 'giallo'],
  ['schwarz', 'nero'],
  ['weiß', 'bianco'],
  ['jetzt', 'adesso'],
  ['später', 'dopo'],
  ['immer', 'sempre'],
  ['manchmal', 'a volte'],
  ['oft', 'spesso'],
  ['der Hund', 'il cane'],
  ['die Katze', 'il gatto'],
  ['Adjektive', 'Aggettivi'],
  ['Menschen & Beziehungen', 'Persone & Relazioni'],
  ['Stadt & Orte', 'Città & Luoghi'],
  ['Essen & Trinken', 'Cibo & Bevande'],
  ['Farben', 'Colori'],
  ['Zeitausdrücke', 'Espressioni di tempo'],
  ['Sport & Bewegung', 'Sport & Movimento'],
  ['Arbeit & Technologie', 'Lavoro & Tecnologia'],
  ['Reisen & Tourismus', 'Viaggi & Turismo'],
  ['Zuhause & Möbel', 'Casa & Mobili'],
  ['Kleidung', 'Abbigliamento'],
  ['Natur & Umwelt', 'Natura & Ambiente'],
  ['Geld & Finanzen', 'Denaro & Finanza'],
  ['Wissenschaft & Forschung', 'Scienza & Ricerca'],
  ['Kunst & Kultur', 'Arte & Cultura'],
  ['Fragewörter', 'Parole interrogative'],
  ['Berufe', 'Professioni'],
  ['Denken & Meinung', 'Pensiero & Opinione'],
  ['Tiere', 'Animali'],
  ['Gesundheitsvokabular', 'Vocabolario salute'],
  ['Akademisches Deutsch', 'Italiano accademico'],
  ['Technologie & Digitales Leben', 'Tecnologia & Vita digitale'],
  ['Soziale Ausdrücke', 'Espressioni sociali'],
  ['Geographie & Welt', 'Geografia & Mondo'],
  ['Aktionsverben', 'Verbi d\\\'azione'],
  ['Geschichte & Gesellschaft', 'Storia & Società'],
  ['Redewendungen & Sprichwörter', 'Modi di dire & Proverbi'],
  ['Gemischte Wiederholung & Fortgeschritten', 'Ripasso misto & Avanzato'],
  ['Hallo, hier ist...', 'Ciao, sono...'],
  ['Hallo, hier ist Ali.', 'Ciao, sono Ali.'],
  ['Guten Tag, Firma Müller. Was kann ich für Sie tun?', 'Buongiorno, ditta Müller. Cosa posso fare per Lei?'],
  ['Guten Tag. Hier ist Ali. Kann ich Herrn Schmidt sprechen?', 'Buongiorno. Sono Ali. Posso parlare con il signor Schmidt?'],
  ['Guten Tag. Ich suche eine Wohnung.', 'Buongiorno. Cerco un appartamento.'],
  ['Ich bin Türke.', 'Sono turco.'],
  ['Ich bin glücklich.', 'Sono felice.'],
  ['Ich bin müde.', 'Sono stanco.'],
  ['Ich bin sehr müde.', 'Sono molto stanco.'],
  ['Ich bin ein bisschen müde. Viel Arbeit.', 'Sono un po\\\' stanco. Molto lavoro.'],
  ['Ich bin der Meinung, dass...', 'Sono dell\\\'opinione che...'],
  ['Ali lernt Deutsch.', 'Ali impara l\\\'italiano.'],
  ['Entschuldigung, ich verstehe nicht.', 'Scusi, non capisco.'],
  ['Können Sie das wiederholen?', 'Può ripetere?'],
  ['Können Sie bitte langsamer sprechen?', 'Può parlare più piano, per favore?'],
];

PHRASES.sort((a, b) => b[0].length - a[0].length);
for (const [de, it] of PHRASES) {
  tail = tail.split(de).join(it);
}

// Drop duplicate buildVocabLesson from German tail (already in header)
tail = tail.replace(
  /function buildVocabLesson\(n, title, entries\) \{[\s\S]*?return vocab\(title, words\);\s*\}\s*\n/,
  ''
);

const out = header + l1l3 + tail;
const fixed = out
  .replace(/(?<!\\)'l'([a-zA-Zàèéìòù])/g, "'l\\'$1")
  .replace(/(?<!\\)dov'è/g, "dov\\'è")
  .replace(/(?<!\\)Dov'è/g, "Dov\\'è")
  .replace(/(?<!\\)cos'è/g, "cos\\'è")
  .replace(/(?<!\\)Cos'è/g, "Cos\\'è")
  .replace(/(?<!\\)\ball'/g, "all\\'")
  .replace(/(?<!\\)\bdell'/g, "dell\\'")
  .replace(/(?<!\\)\bnell'/g, "nell\\'");
writeFileSync(join(__dirname, 'gen-italian-lessons.mjs'), fixed, 'utf8');
console.log('Wrote clean gen-italian-lessons.mjs,', out.split('\n').length, 'lines');
