/** Language configs for HTML app generation */
export const LANGS = {
  it: {
    code: 'it',
    prefix: 'it1_',
    storageBrand: 'italian_',
    flag: '🇮🇹',
    nameTr: 'Kolay İtalyanca',
    nameEn: 'Easy Italian Learning',
    title: 'Kolay İtalyanca Öğrenme',
    htmlFile: 'italian-v3.html',
    lessonsPath: 'languages/it/lessons',
    tts: 'it-IT',
    ttsAlt: 'it-CH',
    ttsPrefix: 'it',
    googleVoiceF: 'it-IT-Wavenet-A',
    googleVoiceM: 'it-IT-Wavenet-C',
    kdoTarget: 'it',
    targetLabelTr: 'İtalyanca',
    targetLabelEn: 'Italian',
    charDetect: '/[àèéìòóù]/',
    l2Meta: {
      title: 'Articoli & essere',
      title_en: 'Articles & essere',
      subtitle: 'il/la/lo — adım adım',
      subtitle_en: 'il/la/lo — step by step',
    },
    numInfoTr: 'İtalyanca sayılarda binlik nokta kullanılır: 1.000. Karta dokun → sesini duy 🔊',
    numInfoEn: 'Italian uses period for thousands: 1.000. Tap a card to hear it 🔊',
  },
  es: {
    code: 'es',
    prefix: 'es1_',
    storageBrand: 'spanish_',
    flag: '🇪🇸',
    nameTr: 'Kolay İspanyolca',
    nameEn: 'Easy Spanish Learning',
    title: 'Kolay İspanyolca Öğrenme',
    htmlFile: 'spanish-v3.html',
    lessonsPath: 'languages/es/lessons',
    tts: 'es-ES',
    ttsAlt: 'es-MX',
    ttsPrefix: 'es',
    googleVoiceF: 'es-ES-Neural2-F',
    googleVoiceM: 'es-ES-Neural2-D',
    kdoTarget: 'es',
    targetLabelTr: 'İspanyolca',
    targetLabelEn: 'Spanish',
    charDetect: '/[áéíóúüñ¿¡]/',
    l2Meta: {
      title: 'Artículos & ser',
      title_en: 'Articles & ser',
      subtitle: 'el/la — adım adım',
      subtitle_en: 'el/la — step by step',
    },
    numInfoTr: 'İspanyolca sayılarda binlik nokta: 1.000. Karta dokun → sesini duy 🔊',
    numInfoEn: 'Spanish uses period for thousands: 1.000. Tap a card to hear it 🔊',
  },
  fr: {
    code: 'fr',
    prefix: 'fr1_',
    storageBrand: 'french_',
    flag: '🇫🇷',
    nameTr: 'Kolay Fransızca',
    nameEn: 'Easy French Learning',
    title: 'Kolay Fransızca Öğrenme',
    htmlFile: 'french-v3.html',
    lessonsPath: 'languages/fr/lessons',
    tts: 'fr-FR',
    ttsAlt: 'fr-CA',
    ttsPrefix: 'fr',
    googleVoiceF: 'fr-FR-Neural2-A',
    googleVoiceM: 'fr-FR-Neural2-D',
    kdoTarget: 'fr',
    targetLabelTr: 'Fransızca',
    targetLabelEn: 'French',
    charDetect: '/[àâæçéèêëîïôùûü]/',
    l2Meta: {
      title: 'Articles & être',
      title_en: 'Articles & être',
      subtitle: "le/la/l' — adım adım",
      subtitle_en: "le/la/l' — step by step",
    },
    numInfoTr: 'Fransızca sayılarda yetmiş (soixante-dix) gibi özel yapılar var. Karta dokun → sesini duy 🔊',
    numInfoEn: 'French has special forms like soixante-dix (70). Tap a card to hear it 🔊',
  },
  ru: {
    code: 'ru',
    prefix: 'ru1_',
    storageBrand: 'russian_',
    flag: '🇷🇺',
    nameTr: 'Kolay Rusça',
    nameEn: 'Easy Russian Learning',
    title: 'Kolay Rusça Öğrenme',
    htmlFile: 'russian-v3.html',
    lessonsPath: 'languages/ru/lessons',
    tts: 'ru-RU',
    ttsAlt: 'ru-RU',
    ttsPrefix: 'ru',
    googleVoiceF: 'ru-RU-Wavenet-A',
    googleVoiceM: 'ru-RU-Wavenet-B',
    kdoTarget: 'ru',
    targetLabelTr: 'Rusça',
    targetLabelEn: 'Russian',
    charDetect: '/[а-яА-ЯёЁ]/',
    l2Meta: {
      title: 'Падежи & быть',
      title_en: 'Cases & быть',
      subtitle: 'именительный — adım adım',
      subtitle_en: 'nominative — step by step',
    },
    numInfoTr: 'Rusça sayılarda 11-19 özel formlar kullanır. Karta dokun → sesini duy 🔊',
    numInfoEn: 'Russian 11-19 use special forms. Tap a card to hear it 🔊',
    rtl: false,
    cjk: false,
  },
  ar: {
    code: 'ar',
    prefix: 'ar1_',
    storageBrand: 'arabic_',
    flag: '🇸🇦',
    nameTr: 'Kolay Arapça',
    nameEn: 'Easy Arabic Learning',
    title: 'Kolay Arapça Öğrenme',
    htmlFile: 'arabic-v3.html',
    lessonsPath: 'languages/ar/lessons',
    tts: 'ar-SA',
    ttsAlt: 'ar-XA',
    ttsPrefix: 'ar',
    googleVoiceF: 'ar-XA-Wavenet-A',
    googleVoiceM: 'ar-XA-Wavenet-B',
    kdoTarget: 'ar',
    targetLabelTr: 'Arapça',
    targetLabelEn: 'Arabic',
    charDetect: '/[\\u0600-\\u06FF]/',
    l2Meta: {
      title: 'أدوات التعريف',
      title_en: 'Definite article ال',
      subtitle: 'ال + güneş/ay harfleri',
      subtitle_en: 'ال + sun/moon letters',
    },
    numInfoTr: 'Arapça sayılar cinsiyete göre değişir. Karta dokun → sesini duy 🔊',
    numInfoEn: 'Arabic numbers vary by gender. Tap a card to hear it 🔊',
    rtl: true,
    cjk: false,
  },
  zh: {
    code: 'zh',
    prefix: 'zh1_',
    storageBrand: 'chinese_',
    flag: '🇨🇳',
    nameTr: 'Kolay Çince',
    nameEn: 'Easy Chinese Learning',
    title: 'Kolay Çince Öğrenme',
    htmlFile: 'chinese-v3.html',
    lessonsPath: 'languages/zh/lessons',
    tts: 'zh-CN',
    ttsAlt: 'zh-TW',
    ttsPrefix: 'zh',
    googleVoiceF: 'cmn-CN-Wavenet-A',
    googleVoiceM: 'cmn-CN-Wavenet-B',
    kdoTarget: 'zh',
    targetLabelTr: 'Çince',
    targetLabelEn: 'Chinese',
    charDetect: '/[\\u4e00-\\u9fff]/',
    l2Meta: {
      title: '量词 & 是',
      title_en: 'Measure words & 是',
      subtitle: '个/位 — adım adım',
      subtitle_en: '个/位 — step by step',
    },
    numInfoTr: 'Çince sayılarda 一 ile 二 ton değişir. Karta dokun → sesini duy 🔊',
    numInfoEn: 'Chinese tones change with 一 and 二. Tap a card to hear it 🔊',
    rtl: false,
    cjk: true,
  },
};
