/** Language configs for HTML app generation */
export const LANGS = {
  de: {
    code: 'de',
    prefix: 'de1_',
    storageBrand: 'german_',
    flag: '🇩🇪',
    nameTr: 'Kolay Almanca',
    nameEn: 'Easy German Learning',
    title: 'Kolay Almanca Öğrenme',
    htmlFile: 'german-v3.html',
    lessonsPath: 'languages/de/lessons',
    tts: 'de-DE',
    ttsAlt: 'de-AT',
    ttsPrefix: 'de',
    googleVoiceF: 'de-DE-Chirp3-HD-Aoede',
    googleVoiceM: 'de-DE-Chirp3-HD-Orus',
    kdoTarget: 'de',
    targetLabelTr: 'Almanca',
    targetLabelEn: 'German',
    translateTarget: 'de',
    translateRe: '/[äöüßÄÖÜ]|(\\b(der|die|das|den|dem|des|ein|eine|und|ist|sind|nicht|ich|du|er|sie|wir|ihr|haben|sein|wird|kann|auch|mit|von|auf|für|aber|oder|wenn|dass|guten|tag|morgen|abend)\\b)/i',
    l2Meta: {
      title: 'Artikel & sein',
      title_en: 'Articles & sein',
      subtitle: 'der/die/das — adım adım',
      subtitle_en: 'der/die/das — step by step',
    },
    numInfoTr: 'Almanca sayılarda birler önce, onlar sonda gelir: 21 = einundzwanzig. Karta dokun → sesini duy 🔊',
    numInfoEn: 'German numbers: ones before tens — 21 = einundzwanzig. Tap a card to hear it 🔊',
    legacy: false,
  },
  en: {
    code: 'en',
    prefix: 'en1_',
    storageBrand: 'english_',
    flag: '🇬🇧',
    nameTr: 'Kolay İngilizce',
    nameEn: 'Easy English Learning',
    title: 'Kolay İngilizce Öğrenme',
    htmlFile: 'english-v3.html',
    lessonsPath: 'languages/en/lessons',
    tts: 'en-US',
    ttsAlt: 'en-GB',
    ttsPrefix: 'en',
    googleVoiceF: 'en-US-Neural2-F',
    googleVoiceM: 'en-US-Neural2-D',
    kdoTarget: 'en',
    targetLabelTr: 'İngilizce',
    targetLabelEn: 'English',
    translateTarget: 'en',
    translateRe: '/\\b(the|is|are|was|were|have|has|had|will|would|can|could|hello|good|morning|please|thank|you|your|my|this|that|what|how|where|when|why)\\b/i',
    l2Meta: {
      title: 'Fiil Zamanları',
      title_en: 'Verb Tenses',
      subtitle: 'Present / Past — adım adım',
      subtitle_en: 'Present / Past — step by step',
    },
    numInfoTr: 'İngilizce sayılarda birler önce gelir: 21 = twenty-one. Karta dokun → sesini duy 🔊',
    numInfoEn: 'English numbers: ones before tens — 21 = twenty-one. Tap a card to hear it 🔊',
    legacy: false,
    enLesson2Migration: true,
  },
  it: {
    code: 'it',
    prefix: 'it1_',
    storageBrand: 'italian_',
    flag: '🇮🇹',
    nameTr: 'Kolay İtalyanca',
    nameEn: 'Easy Italian Learning',
    title: 'Kolay İtalyanca Öğrenme',
    htmlFile: 'italian-v3.html',
    lessonsPath: 'languages/it/lessons',
    tts: 'it-IT',
    ttsAlt: 'it-CH',
    ttsPrefix: 'it',
    googleVoiceF: 'it-IT-Wavenet-A',
    googleVoiceM: 'it-IT-Wavenet-C',
    kdoTarget: 'it',
    targetLabelTr: 'İtalyanca',
    targetLabelEn: 'Italian',
    charDetect: '/[àèéìòóù]/',
    l2Meta: {
      title: 'Articoli & essere',
      title_en: 'Articles & essere',
      subtitle: 'il/la/lo — adım adım',
      subtitle_en: 'il/la/lo — step by step',
    },
    numInfoTr: 'İtalyanca sayılarda binlik nokta kullanılır: 1.000. Karta dokun → sesini duy 🔊',
    numInfoEn: 'Italian uses period for thousands: 1.000. Tap a card to hear it 🔊',
    translateTarget: 'it',
    translateRe: '/[àèéìòù]|(\\b(il|lo|la|i|gli|le|un|una|io|tu|lui|lei|ciao|grazie|è|sono|non|con|per)\\b)/i',
    legacy: false,
  },
  es: {
    code: 'es',
    prefix: 'es1_',
    storageBrand: 'spanish_',
    flag: '🇪🇸',
    nameTr: 'Kolay İspanyolca',
    nameEn: 'Easy Spanish Learning',
    title: 'Kolay İspanyolca Öğrenme',
    htmlFile: 'spanish-v3.html',
    lessonsPath: 'languages/es/lessons',
    tts: 'es-ES',
    ttsAlt: 'es-MX',
    ttsPrefix: 'es',
    googleVoiceF: 'es-ES-Neural2-F',
    googleVoiceM: 'es-ES-Neural2-D',
    kdoTarget: 'es',
    targetLabelTr: 'İspanyolca',
    targetLabelEn: 'Spanish',
    charDetect: '/[áéíóúüñ¿¡]/',
    l2Meta: {
      title: 'Artículos & ser',
      title_en: 'Articles & ser',
      subtitle: 'el/la — adım adım',
      subtitle_en: 'el/la — step by step',
    },
    numInfoTr: 'İspanyolca sayılarda binlik nokta: 1.000. Karta dokun → sesini duy 🔊',
    numInfoEn: 'Spanish uses period for thousands: 1.000. Tap a card to hear it 🔊',
    translateTarget: 'es',
    translateRe: '/[áéíóúüñ¿¡]|(\\b(el|la|los|las|un|una|yo|tú|él|hola|gracias|sí|no|es|son|con|para|por)\\b)/i',
    legacy: false,
  },
  fr: {
    code: 'fr',
    prefix: 'fr1_',
    storageBrand: 'french_',
    flag: '🇫🇷',
    nameTr: 'Kolay Fransızca',
    nameEn: 'Easy French Learning',
    title: 'Kolay Fransızca Öğrenme',
    htmlFile: 'french-v3.html',
    lessonsPath: 'languages/fr/lessons',
    tts: 'fr-FR',
    ttsAlt: 'fr-CA',
    ttsPrefix: 'fr',
    googleVoiceF: 'fr-FR-Neural2-A',
    googleVoiceM: 'fr-FR-Neural2-D',
    kdoTarget: 'fr',
    targetLabelTr: 'Fransızca',
    targetLabelEn: 'French',
    charDetect: '/[àâæçéèêëîïôùûü]/',
    l2Meta: {
      title: 'Articles & être',
      title_en: 'Articles & être',
      title_th: 'คำนำหน้านามและ être',
      subtitle: "le/la/l' — adım adım",
      subtitle_en: "le/la/l' — step by step",
      subtitle_th: "le/la/l' — ทีละขั้น",
    },
    numInfoTr: 'Fransızca sayılarda yetmiş (soixante-dix) gibi özel yapılar var. Karta dokun → sesini duy 🔊',
    numInfoEn: 'French has special forms like soixante-dix (70). Tap a card to hear it 🔊',
    translateTarget: 'fr',
    translateRe: '/[àâæçéèêëîïôùûüœÀÂÆÇÉÈÊËÎÏÔÙÛÜŒ]|(\\b(le|la|les|un|une|des|je|tu|il|elle|nous|vous|ils|bonjour|merci|oui|non|est|sont|pas|avec|pour)\\b)/i',
    legacy: false,
  },
  ru: {
    code: 'ru',
    prefix: 'ru1_',
    storageBrand: 'russian_',
    flag: '🇷🇺',
    nameTr: 'Kolay Rusça',
    nameEn: 'Easy Russian Learning',
    title: 'Kolay Rusça Öğrenme',
    htmlFile: 'russian-v3.html',
    lessonsPath: 'languages/ru/lessons',
    tts: 'ru-RU',
    ttsAlt: 'ru-RU',
    ttsPrefix: 'ru',
    googleVoiceF: 'ru-RU-Wavenet-A',
    googleVoiceM: 'ru-RU-Wavenet-B',
    kdoTarget: 'ru',
    targetLabelTr: 'Rusça',
    targetLabelEn: 'Russian',
    charDetect: '/[а-яА-ЯёЁ]/',
    l2Meta: {
      title: 'Падежи & быть',
      title_en: 'Cases & быть',
      subtitle: 'именительный — adım adım',
      subtitle_en: 'nominative — step by step',
    },
    numInfoTr: 'Rusça sayılarda 11-19 özel formlar kullanır. Karta dokun → sesini duy 🔊',
    numInfoEn: 'Russian 11-19 use special forms. Tap a card to hear it 🔊',
    translateTarget: 'ru',
    translateRe: '/[а-яА-ЯёЁ]/',
    rtl: false,
    cjk: false,
    legacy: false,
  },
  ar: {
    code: 'ar',
    prefix: 'ar1_',
    storageBrand: 'arabic_',
    flag: '🇸🇦',
    nameTr: 'Kolay Arapça',
    nameEn: 'Easy Arabic Learning',
    title: 'Kolay Arapça Öğrenme',
    htmlFile: 'arabic-v3.html',
    lessonsPath: 'languages/ar/lessons',
    tts: 'ar-SA',
    ttsAlt: 'ar-XA',
    ttsPrefix: 'ar',
    googleVoiceF: 'ar-XA-Wavenet-A',
    googleVoiceM: 'ar-XA-Wavenet-B',
    kdoTarget: 'ar',
    targetLabelTr: 'Arapça',
    targetLabelEn: 'Arabic',
    charDetect: '/[\\u0600-\\u06FF]/',
    l2Meta: {
      title: 'أدوات التعريف',
      title_en: 'Definite article ال',
      subtitle: 'ال + güneş/ay harfleri',
      subtitle_en: 'ال + sun/moon letters',
    },
    numInfoTr: 'Arapça sayılar cinsiyete göre değişir. Karta dokun → sesini duy 🔊',
    numInfoEn: 'Arabic numbers vary by gender. Tap a card to hear it 🔊',
    translateTarget: 'ar',
    translateRe: '/[\\u0600-\\u06FF]/',
    rtl: true,
    cjk: false,
    legacy: false,
  },
  zh: {
    code: 'zh',
    prefix: 'zh1_',
    storageBrand: 'chinese_',
    flag: '🇨🇳',
    nameTr: 'Kolay Çince',
    nameEn: 'Easy Chinese Learning',
    title: 'Kolay Çince Öğrenme',
    htmlFile: 'chinese-v3.html',
    lessonsPath: 'languages/zh/lessons',
    tts: 'zh-CN',
    ttsAlt: 'zh-TW',
    ttsPrefix: 'zh',
    googleVoiceF: 'cmn-CN-Wavenet-A',
    googleVoiceM: 'cmn-CN-Wavenet-B',
    kdoTarget: 'zh',
    targetLabelTr: 'Çince',
    targetLabelEn: 'Chinese',
    charDetect: '/[\\u4e00-\\u9fff]/',
    l2Meta: {
      title: '量词 & 是',
      title_en: 'Measure words & 是',
      subtitle: '个/位 — adım adım',
      subtitle_en: '个/位 — step by step',
    },
    numInfoTr: 'Çince sayılarda 一 ile 二 ton değişir. Karta dokun → sesini duy 🔊',
    numInfoEn: 'Chinese tones change with 一 and 二. Tap a card to hear it 🔊',
    translateTarget: 'zh-CN',
    translateRe: '/[\\u4e00-\\u9fff]/',
    rtl: false,
    cjk: false,
    legacy: false,
  },
  tk: {
    code: 'tk',
    prefix: 'tk1_',
    storageBrand: 'turkish_',
    flag: '🇹🇷',
    nameTr: 'Kolay Türkçe',
    nameEn: 'Easy Turkish Learning',
    title: 'Kolay Türkçe Öğrenme',
    htmlFile: 'turkish-v3.html',
    lessonsPath: 'languages/tr/lessons',
    tts: 'tr-TR',
    ttsAlt: 'tr-TR',
    ttsPrefix: 'tr',
    googleVoiceF: 'tr-TR-Wavenet-A',
    googleVoiceM: 'tr-TR-Wavenet-B',
    kdoTarget: 'tk',
    targetLabelTr: 'Türkçe',
    targetLabelEn: 'Turkish',
    charDetect: '/[çğıöşüÇĞİÖŞÜ]/',
    l2Meta: {
      title: 'Ekler & -de/-da',
      title_en: 'Suffixes & -de/-da',
      subtitle: 'ünlü uyumu — adım adım',
      subtitle_en: 'vowel harmony — step by step',
    },
    numInfoTr: 'Türkçe sayılarda birler önce gelir: 21 = yirmi bir. Karta dokun → sesini duy 🔊',
    numInfoEn: 'Turkish numbers: ones before tens — 21 = yirmi bir. Tap a card to hear it 🔊',
    translateTarget: 'tr',
    translateRe: '/[çğıöşüÇĞİÖŞÜ]/',
    translateFallback: 'en',
    translateLessonTarget: 'tr',
    translateLessonBase: 'en',
    extras: ['gram-turkish'],
    rtl: false,
    cjk: false,
    legacy: false,
  },
  th: {
    code: 'th',
    prefix: 'tv3_',
    storageBrand: 'thai_',
    flag: '🇹🇭',
    nameTr: 'Kolay Tayca',
    nameEn: 'Easy Thai Learning',
    title: 'Kolay Tayca Öğrenme',
    htmlFile: 'tayca-v3.html',
    lessonsPath: 'languages/th/lessons',
    tts: 'th-TH',
    ttsAlt: 'th-TH',
    ttsPrefix: 'th',
    googleVoiceF: 'th-TH-Neural2-C',
    googleVoiceM: 'th-TH-Neural2-C',
    kdoTarget: 'th',
    targetLabelTr: 'Tayca',
    targetLabelEn: 'Thai',
    translateTarget: 'th',
    translateRe: '/[\\u0E00-\\u0E7F]/',
    translateFallback: 'tr',
    translateLessonTarget: 'th',
    translateLessonBase: 'tr',
    legacy: true,
    legacyUrl: 'tayca-v3.html',
  },
  ha: {
    code: 'ha',
    prefix: 'ha1_',
    storageBrand: 'hausa_',
    flag: '🇳🇬',
    nameTr: 'Kolay Hausa',
    nameEn: 'Easy Hausa Learning',
    title: 'Kolay Hausa Öğrenme',
    lessonsPath: 'languages/ha/lessons',
    tts: 'ha-NG',
    ttsAlt: 'ha',
    ttsPrefix: 'ha',
    googleVoiceF: '',
    googleVoiceM: '',
    kdoTarget: 'ha',
    targetLabelTr: 'Hausa',
    targetLabelEn: 'Hausa',
    translateTarget: 'ha',
    translateRe: '/\\b(sannu|ina|kwana|nagode|yauwa|sunana|lafiya|godiya|don|allah|zan|zo|ban|ba)\\b/i',
    translateFallback: 'en',
    translateLessonTarget: 'ha',
    translateLessonBase: 'tr',
    l2Meta: {
      title: 'Sayılar ve Para',
      title_en: 'Numbers & Money',
      subtitle: 'lambobi — adım adım',
      subtitle_en: 'numbers — step by step',
    },
    numInfoTr: 'Hausa sayılarında Arapça kökenli kelimeler kullanılır. Karta dokun → sesini duy 🔊',
    numInfoEn: 'Hausa numbers use Arabic-derived words. Tap a card to hear it 🔊',
    lessonsCount: 20,
    legacy: false,
  },
  sw: {
    code: 'sw',
    prefix: 'sw1_',
    storageBrand: 'swahili_',
    flag: '🇹🇿',
    nameTr: 'Kolay Svahili',
    nameEn: 'Easy Swahili Learning',
    title: 'Kolay Svahili Öğrenme',
    lessonsPath: 'languages/sw/lessons',
    tts: 'sw-TZ',
    ttsAlt: 'sw-KE',
    ttsPrefix: 'sw',
    googleVoiceF: '',
    googleVoiceM: '',
    kdoTarget: 'sw',
    targetLabelTr: 'Svahili',
    targetLabelEn: 'Swahili',
    translateTarget: 'sw',
    translateRe: '/\\b(jambo|habari|asante|karibu|ndiyo|hapana|mimi|wewe|nina|una|tafadhali|pole|kwaheri|jina|shilingi|safari|hospitali|chakula|maji)\\b/i',
    translateFallback: 'en',
    translateLessonTarget: 'sw',
    translateLessonBase: 'tr',
    l2Meta: {
      title: 'Nambari na Pesa',
      title_en: 'Numbers & Money',
      title_th: 'ตัวเลขและเงิน',
      subtitle: 'moja, mbili, tatu — hatua kwa hatua',
      subtitle_en: 'moja, mbili, tatu — step by step',
    },
    numInfoTr: 'Svahilice sayılarda onluk sistem kullanılır: 21 = ishirini na moja. Karta dokun → sesini duy 🔊',
    numInfoEn: 'Swahili uses tens + ones: 21 = ishirini na moja. Tap a card to hear it 🔊',
    lessonsCount: 20,
    legacy: false,
  },
};
