/** Language configs for HTML app generation */
export const LANGS = {
  it: {
    code: 'it',
    prefix: 'it1_',
    storageBrand: 'italian_',
    flag: '🇮🇹',
    nameTr: 'Kolay İtalyanca',
    nameEn: 'Easy Italian Learning',
    title: 'Kolay İtalyanca Öğrenme',
    htmlFile: 'italian-v3.html',
    lessonsPath: 'languages/it/lessons',
    tts: 'it-IT',
    ttsAlt: 'it-CH',
    ttsPrefix: 'it',
    googleVoiceF: 'it-IT-Wavenet-A',
    googleVoiceM: 'it-IT-Wavenet-C',
    kdoTarget: 'it',
    targetLabelTr: 'İtalyanca',
    targetLabelEn: 'Italian',
    charDetect: '/[àèéìòóù]/',
    l2Meta: {
      title: 'Articoli & essere',
      title_en: 'Articles & essere',
      subtitle: 'il/la/lo — adım adım',
      subtitle_en: 'il/la/lo — step by step',
    },
    numInfoTr: 'İtalyanca sayılarda binlik nokta kullanılır: 1.000. Karta dokun → sesini duy 🔊',
    numInfoEn: 'Italian uses period for thousands: 1.000. Tap a card to hear it 🔊',
  },
  es: {
    code: 'es',
    prefix: 'es1_',
    storageBrand: 'spanish_',
    flag: '🇪🇸',
    nameTr: 'Kolay İspanyolca',
    nameEn: 'Easy Spanish Learning',
    title: 'Kolay İspanyolca Öğrenme',
    htmlFile: 'spanish-v3.html',
    lessonsPath: 'languages/es/lessons',
    tts: 'es-ES',
    ttsAlt: 'es-MX',
    ttsPrefix: 'es',
    googleVoiceF: 'es-ES-Neural2-F',
    googleVoiceM: 'es-ES-Neural2-D',
    kdoTarget: 'es',
    targetLabelTr: 'İspanyolca',
    targetLabelEn: 'Spanish',
    charDetect: '/[áéíóúüñ¿¡]/',
    l2Meta: {
      title: 'Artículos & ser',
      title_en: 'Articles & ser',
      subtitle: 'el/la — adım adım',
      subtitle_en: 'el/la — step by step',
    },
    numInfoTr: 'İspanyolca sayılarda binlik nokta: 1.000. Karta dokun → sesini duy 🔊',
    numInfoEn: 'Spanish uses period for thousands: 1.000. Tap a card to hear it 🔊',
  },
  fr: {
    code: 'fr',
    prefix: 'fr1_',
    storageBrand: 'french_',
    flag: '🇫🇷',
    nameTr: 'Kolay Fransızca',
    nameEn: 'Easy French Learning',
    title: 'Kolay Fransızca Öğrenme',
    htmlFile: 'french-v3.html',
    lessonsPath: 'languages/fr/lessons',
    tts: 'fr-FR',
    ttsAlt: 'fr-CA',
    ttsPrefix: 'fr',
    googleVoiceF: 'fr-FR-Neural2-A',
    googleVoiceM: 'fr-FR-Neural2-D',
    kdoTarget: 'fr',
    targetLabelTr: 'Fransızca',
    targetLabelEn: 'French',
    charDetect: '/[àâæçéèêëîïôùûü]/',
    l2Meta: {
      title: 'Articles & être',
      title_en: 'Articles & être',
      subtitle: "le/la/l' — adım adım",
      subtitle_en: "le/la/l' — step by step",
    },
    numInfoTr: 'Fransızca sayılarda yetmiş (soixante-dix) gibi özel yapılar var. Karta dokun → sesini duy 🔊',
    numInfoEn: 'French has special forms like soixante-dix (70). Tap a card to hear it 🔊',
  },
};
